### ISSUE TITLE
bug: dev conda enviornment not working with sphinx 8.1.0

### ISSUE THREAD

**Issue by ncclementi** [rapidsai/deployment#463]
I was trying to install the dev dependencies following the instruction from the readme, and with the latest release (v8.1.0 released recently) I get an error when trying to do `make dirhtml`

```bash
Running Sphinx v8.1.0
loading translations [en]... done

Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ExtensionError' from 'sphinx.util' (.../miniforge3/envs/deployment-docs-dev/lib/python3.12/site-packages/sphinx/util/__init__.py))
make: *** [dirhtml] Error 2
```

If I downgrade to `sphinx=8.0.2` the problem is resolved. Not sure exactly what the problem is but a potential temporary solution would be to pin sphinx. Happy to open a PR, if you think this is the right way to do go about it.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @ncclementi! Yeah it looks like `8.1.0` released yesterday and broke the build here. Pinning would be good but I expect a fix either needs to go into `sphinx` or `sphinxcontrib-mermaid ` to fix this properly.

**Comment by jacobtomlinson** [comment]
I've opened #469 to add an upper bound to Sphinx and also https://github.com/mgaitan/sphinxcontrib-mermaid/pull/161 to fix this upstream.

**Comment by jameslamb** [comment]
Thanks for handling this @jacobtomlinson !
